/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato;

import gato.Gato_Metodos;

/**
 *
 * @author Cristiam
 */
public class Frm_NuevoJuego extends javax.swing.JInternalFrame {

    Gato_Metodos jugador = new Gato_Metodos();

    /**
     * Creates new form Frm_NuevoJuego
     */
    public Frm_NuevoJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_jugador1 = new javax.swing.JPanel();
        Rdb_ListaJugador1 = new javax.swing.JRadioButton();
        Rdb_NuevoJugador1 = new javax.swing.JRadioButton();
        txt_NuevoJugador1 = new javax.swing.JTextField();
        Cbx_ListaJ1 = new javax.swing.JComboBox<>();
        Lb_rifa1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Panel_jugador2 = new javax.swing.JPanel();
        Rdb_ListaJugador2 = new javax.swing.JRadioButton();
        Rdb_NuevoJugador2 = new javax.swing.JRadioButton();
        txt_NuevoJugador2 = new javax.swing.JTextField();
        Cbx_ListaJ2 = new javax.swing.JComboBox<>();
        Lb_rifa2 = new javax.swing.JLabel();
        Panel_jugador3 = new javax.swing.JPanel();
        Rdb_ListaJugador3 = new javax.swing.JRadioButton();
        Rdb_NuevoJugador3 = new javax.swing.JRadioButton();
        txt_NuevoJugador3 = new javax.swing.JTextField();
        Lb_rifa3 = new javax.swing.JLabel();
        Cbx_ListaJ3 = new javax.swing.JComboBox<>();
        Btn_Jugar = new javax.swing.JLabel();
        Btn_rifa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lb_Ficha1 = new javax.swing.JLabel();
        Lb_Ficha2 = new javax.swing.JLabel();

        Panel_jugador1.setBackground(new java.awt.Color(255, 255, 255));
        Panel_jugador1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3), "Jugador 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 0, 14), new java.awt.Color(0, 51, 153))); // NOI18N
        Panel_jugador1.setForeground(new java.awt.Color(0, 0, 102));

        Rdb_ListaJugador1.setBackground(new java.awt.Color(255, 255, 255));
        Rdb_ListaJugador1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        Rdb_ListaJugador1.setForeground(new java.awt.Color(0, 0, 102));
        Rdb_ListaJugador1.setText("Lista de Jugadores");
        Rdb_ListaJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_ListaJugador1ActionPerformed(evt);
            }
        });

        Rdb_NuevoJugador1.setBackground(new java.awt.Color(255, 255, 255));
        Rdb_NuevoJugador1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        Rdb_NuevoJugador1.setForeground(new java.awt.Color(0, 0, 102));
        Rdb_NuevoJugador1.setText("Nuevo Jugador");
        Rdb_NuevoJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_NuevoJugador1ActionPerformed(evt);
            }
        });

        txt_NuevoJugador1.setEnabled(false);

        Cbx_ListaJ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        Cbx_ListaJ1.setEnabled(false);

        javax.swing.GroupLayout Panel_jugador1Layout = new javax.swing.GroupLayout(Panel_jugador1);
        Panel_jugador1.setLayout(Panel_jugador1Layout);
        Panel_jugador1Layout.setHorizontalGroup(
            Panel_jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_jugador1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rdb_NuevoJugador1)
                    .addComponent(Rdb_ListaJugador1))
                .addGap(18, 18, 18)
                .addGroup(Panel_jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cbx_ListaJ1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_jugador1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_NuevoJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(Panel_jugador1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(Lb_rifa1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_jugador1Layout.setVerticalGroup(
            Panel_jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_jugador1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rdb_ListaJugador1)
                    .addComponent(Cbx_ListaJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_rifa1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rdb_NuevoJugador1)
                    .addComponent(txt_NuevoJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_jugador2.setBackground(new java.awt.Color(255, 255, 255));
        Panel_jugador2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3), "Jugador 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 0, 14), new java.awt.Color(0, 51, 153))); // NOI18N
        Panel_jugador2.setForeground(new java.awt.Color(0, 0, 102));
        Panel_jugador2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rdb_ListaJugador2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rdb_ListaJugador2);
        Rdb_ListaJugador2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        Rdb_ListaJugador2.setForeground(new java.awt.Color(0, 0, 102));
        Rdb_ListaJugador2.setText("Lista de Jugadores");
        Rdb_ListaJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_ListaJugador2ActionPerformed(evt);
            }
        });
        Panel_jugador2.add(Rdb_ListaJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 28, -1, -1));

        Rdb_NuevoJugador2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rdb_NuevoJugador2);
        Rdb_NuevoJugador2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        Rdb_NuevoJugador2.setForeground(new java.awt.Color(0, 0, 102));
        Rdb_NuevoJugador2.setText("Nuevo Jugador");
        Rdb_NuevoJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_NuevoJugador2ActionPerformed(evt);
            }
        });
        Panel_jugador2.add(Rdb_NuevoJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 122, -1, -1));

        txt_NuevoJugador2.setEnabled(false);
        Panel_jugador2.add(txt_NuevoJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 125, 127, -1));

        Cbx_ListaJ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        Cbx_ListaJ2.setEnabled(false);
        Panel_jugador2.add(Cbx_ListaJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 31, 127, -1));
        Panel_jugador2.add(Lb_rifa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 79, 57));

        jPanel1.add(Panel_jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 170));

        Panel_jugador3.setBackground(new java.awt.Color(255, 255, 255));
        Panel_jugador3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3), "Jugador 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 0, 14), new java.awt.Color(0, 51, 153))); // NOI18N
        Panel_jugador3.setForeground(new java.awt.Color(0, 0, 102));
        Panel_jugador3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rdb_ListaJugador3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rdb_ListaJugador3);
        Rdb_ListaJugador3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        Rdb_ListaJugador3.setForeground(new java.awt.Color(0, 0, 102));
        Rdb_ListaJugador3.setText("Lista de Jugadores");
        Rdb_ListaJugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_ListaJugador3ActionPerformed(evt);
            }
        });
        Panel_jugador3.add(Rdb_ListaJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 28, -1, -1));

        Rdb_NuevoJugador3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rdb_NuevoJugador3);
        Rdb_NuevoJugador3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        Rdb_NuevoJugador3.setForeground(new java.awt.Color(0, 0, 102));
        Rdb_NuevoJugador3.setText("Nuevo Jugador");
        Rdb_NuevoJugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_NuevoJugador3ActionPerformed(evt);
            }
        });
        Panel_jugador3.add(Rdb_NuevoJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 122, -1, -1));

        txt_NuevoJugador3.setEnabled(false);
        Panel_jugador3.add(txt_NuevoJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 125, 131, -1));
        Panel_jugador3.add(Lb_rifa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 57, 55));

        Cbx_ListaJ3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        Cbx_ListaJ3.setEnabled(false);
        Panel_jugador3.add(Cbx_ListaJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 31, 131, -1));

        jPanel1.add(Panel_jugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 320, 170));

        Btn_Jugar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristiam\\Desktop\\button-play.png")); // NOI18N
        Btn_Jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_JugarMouseClicked(evt);
            }
        });
        jPanel1.add(Btn_Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 120, 110));

        Btn_rifa.setBackground(new java.awt.Color(0, 51, 102));
        Btn_rifa.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        Btn_rifa.setForeground(new java.awt.Color(255, 255, 255));
        Btn_rifa.setText("Rifa");
        Btn_rifa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_rifaMouseClicked(evt);
            }
        });
        jPanel1.add(Btn_rifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("VS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));
        jPanel1.add(lb_Ficha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, 80));
        jPanel1.add(Lb_Ficha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 80, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rdb_ListaJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_ListaJugador1ActionPerformed

    }//GEN-LAST:event_Rdb_ListaJugador1ActionPerformed

    private void Rdb_NuevoJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_NuevoJugador1ActionPerformed

    }//GEN-LAST:event_Rdb_NuevoJugador1ActionPerformed

    private void Rdb_ListaJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_ListaJugador2ActionPerformed
        txt_NuevoJugador2.enable(false);
        Cbx_ListaJ2.enable(true);
    }//GEN-LAST:event_Rdb_ListaJugador2ActionPerformed

    private void Rdb_NuevoJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_NuevoJugador2ActionPerformed
        txt_NuevoJugador2.enable(true);
        Cbx_ListaJ2.enable(false);
    }//GEN-LAST:event_Rdb_NuevoJugador2ActionPerformed

    private void Rdb_ListaJugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_ListaJugador3ActionPerformed
        txt_NuevoJugador3.enable(false);
        Cbx_ListaJ3.enable(true);
    }//GEN-LAST:event_Rdb_ListaJugador3ActionPerformed

    private void Rdb_NuevoJugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_NuevoJugador3ActionPerformed
        txt_NuevoJugador3.enable(true);
        Cbx_ListaJ3.enable(false);
    }//GEN-LAST:event_Rdb_NuevoJugador3ActionPerformed

    private void Btn_rifaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_rifaMouseClicked

        int rifa = (int) (Math.random() * 6);

        conexionDB cone = new conexionDB();
        cone.conexionDB();
        String pribe = "manuel";
        int gane = 2;
        int perdida = 3;
        int empate = 4;
        cone.InsertarJugador(pribe, gane, perdida, empate);
    }//GEN-LAST:event_Btn_rifaMouseClicked

    private void Btn_JugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_JugarMouseClicked
        if (Rdb_ListaJugador2.isSelected()) {
            jugador.jugador1.Nombre = txt_NuevoJugador2.getText();
        }
        else if (Rdb_NuevoJugador2.isSelected()) {
            jugador.jugador1.Nombre = txt_NuevoJugador2.getText();
        }
        else if (Rdb_ListaJugador3.isSelected()) {
            jugador.jugador2.Nombre = txt_NuevoJugador2.getText();
        }
        else if (Rdb_NuevoJugador3.isSelected()) {
            jugador.jugador2.Nombre = txt_NuevoJugador3.getText();
        }
        

    }//GEN-LAST:event_Btn_JugarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_Jugar;
    private javax.swing.JButton Btn_rifa;
    private javax.swing.JComboBox<String> Cbx_ListaJ1;
    private javax.swing.JComboBox<String> Cbx_ListaJ2;
    private javax.swing.JComboBox<String> Cbx_ListaJ3;
    private javax.swing.JLabel Lb_Ficha2;
    private javax.swing.JLabel Lb_rifa1;
    private javax.swing.JLabel Lb_rifa2;
    private javax.swing.JLabel Lb_rifa3;
    private javax.swing.JPanel Panel_jugador1;
    private javax.swing.JPanel Panel_jugador2;
    private javax.swing.JPanel Panel_jugador3;
    private javax.swing.JRadioButton Rdb_ListaJugador1;
    private javax.swing.JRadioButton Rdb_ListaJugador2;
    private javax.swing.JRadioButton Rdb_ListaJugador3;
    private javax.swing.JRadioButton Rdb_NuevoJugador1;
    private javax.swing.JRadioButton Rdb_NuevoJugador2;
    private javax.swing.JRadioButton Rdb_NuevoJugador3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_Ficha1;
    private javax.swing.JTextField txt_NuevoJugador1;
    private javax.swing.JTextField txt_NuevoJugador2;
    private javax.swing.JTextField txt_NuevoJugador3;
    // End of variables declaration//GEN-END:variables
}
